---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "ms-demo-tekton.fullname" . }}-github-ssh-key
spec:
  backendType: vault
  vaultMountPoint: demo
  vaultRole: kes
  data:
  - name: ssh-privatekey
    key: {{ .Values.github.githubVaultSecret }}
    property: {{ .Values.github.privateKeyProperty }}
  template:
    type: kubernetes.io/ssh-auth
    metadata:
      annotations:
        tekton.dev/git-0: github.com
      labels:
        {{- include "ms-demo-tekton.labels" . | nindent 8 }}
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "ms-demo-tekton.fullname" . }}-docker-creds
spec:
  backendType: vault
  vaultMountPoint: demo
  vaultRole: kes
  data:
  - name: username
    key: {{ .Values.registry.registryVaultSecret }}
    property: {{ .Values.registry.usernameProperty }}
  - name: password
    key: {{ .Values.registry.registryVaultSecret }}
    property: {{ .Values.registry.passwordProperty }}
  template:
    type: kubernetes.io/basic-auth
    metadata:
      annotations:
        tekton.dev/docker-0: {{ .Values.registry.url }}
      labels:
        {{- include "ms-demo-tekton.labels" . | nindent 8 }}
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "ms-demo-tekton.fullname" . }}-webhook-secret
spec:
  backendType: vault
  vaultMountPoint: demo
  vaultRole: kes
  data:
  - name: token
    key: {{ .Values.github.githubVaultSecret }}
    property: {{ .Values.github.tokenProperty }}
  - name: secret
    key: {{ .Values.github.githubVaultSecret }}
    property: {{ .Values.github.secretProperty }}
  template:
    metadata:
      labels:
        {{- include "ms-demo-tekton.labels" . | nindent 8 }}
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "ms-demo-tekton.fullname" . }}-argocd-secret
spec:
  backendType: vault
  vaultMountPoint: demo
  vaultRole: kes
  data:
  - name: username
    key: {{ .Values.argocd.argocdVaultSecret }}
    property: {{ .Values.argocd.usernameProperty }}
  - name: password
    key: {{ .Values.argocd.argocdVaultSecret }}
    property: {{ .Values.argocd.passwordProperty }}
  template:
    metadata:
      labels:
        {{- include "ms-demo-tekton.labels" . | nindent 8 }}
---
